version: '3'
 
networks:
  dns_net:
    driver: bridge
    ipam:
        config:
        - subnet: 172.20.0.0/16
 
services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    networks:
      dns_net:
        ipv4_address: 172.20.0.6
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/udp"
      - "80:80/tcp"
    environment:
      TZ: "America/New_York"
      WEBPASSWORD: "password"
      DNS1: "172.20.0.7#5053"
      DNS2: "no"
    volumes:
      - "$PWD/etc-pihole/:/etc/pihole/"
      - "$PWD/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    restart: always

  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      dns_net:
        ipv4_address: 172.20.0.7
    volumes:
      - "$PWD/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf"
      - "$PWD/unbound/resolv.conf:/etc/resolv.conf"
    healthcheck:
      disable: true
    restart: always
